// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieAPI.DataAccess;

#nullable disable

namespace MovieAPI.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Film_API.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Iron Man",
                            Gender = "Male",
                            Name = "Robert Downey Jr",
                            Picture = "https://www.imdb.com/name/nm0000375/?ref_=tt_cl_t_1"
                        },
                        new
                        {
                            Id = 2,
                            Alias = "Black Widow",
                            Gender = "Female",
                            Name = "Scarlett Johansson",
                            Picture = "https://www.imdb.com/name/nm0424060/?ref_=tt_cl_t_5"
                        },
                        new
                        {
                            Id = 3,
                            Alias = "The Joker",
                            Gender = "Male",
                            Name = "Jared Leto",
                            Picture = "https://www.imdb.com/name/nm0001467/?ref_=tt_cl_t_2"
                        },
                        new
                        {
                            Id = 4,
                            Alias = "Harley Quinn",
                            Gender = "Female",
                            Name = "Margot Robbie",
                            Picture = "https://www.imdb.com/name/nm3053338/?ref_=tt_cl_t_3"
                        },
                        new
                        {
                            Id = 5,
                            Alias = "Star Lord",
                            Gender = "Male",
                            Name = "Chris Pratt",
                            Picture = "https://www.imdb.com/name/nm0695435/?ref_=tt_cl_i_1"
                        },
                        new
                        {
                            Id = 6,
                            Alias = "Mantis",
                            Gender = "Female",
                            Name = "Pom Klementieff",
                            Picture = "https://www.imdb.com/name/nm2962353/?ref_=tt_cl_t_4"
                        });
                });

            modelBuilder.Entity("Film_API.Models.CharacterMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterMovies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CharacterId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            CharacterId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            CharacterId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            CharacterId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            CharacterId = 5
                        },
                        new
                        {
                            MovieId = 3,
                            CharacterId = 6
                        });
                });

            modelBuilder.Entity("Film_API.Models.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Franchises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Marvel Cinematic Universe (MCU) films are a series of American superhero films produced by Marvel Studios based on characters that appear in publications by Marvel Comics.",
                            Name = "Marvel"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The DC Universe (DCU) is an upcoming American media franchise and shared universe based on characters from DC Comics publications.",
                            Name = "DC"
                        });
                });

            modelBuilder.Entity("Film_API.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Director")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Trailer")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Anthony Russo",
                            FranchiseId = 1,
                            Genre = "Action",
                            Picture = "x",
                            Title = "Avengers: Endgame",
                            Trailer = "https://www.youtube.com/watch?v=hA6hldpSTF8",
                            Year = 2019
                        },
                        new
                        {
                            Id = 2,
                            Director = "David Ayer",
                            FranchiseId = 2,
                            Genre = "Fantasy",
                            Picture = "x",
                            Title = "Suicide Squad",
                            Trailer = "https://www.youtube.com/watch?v=CmRih_VtVAs",
                            Year = 2016
                        },
                        new
                        {
                            Id = 3,
                            Director = "James Gunn",
                            FranchiseId = 1,
                            Genre = "Action",
                            Picture = "x",
                            Title = "Guardians of the Galaxy",
                            Trailer = "https://www.youtube.com/watch?v=0t2bmsXeFYE",
                            Year = 2014
                        });
                });

            modelBuilder.Entity("Film_API.Models.CharacterMovie", b =>
                {
                    b.HasOne("Film_API.Models.Character", "Character")
                        .WithMany("CharacterMovies")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Film_API.Models.Movie", "Movie")
                        .WithMany("CharacterMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Film_API.Models.Movie", b =>
                {
                    b.HasOne("Film_API.Models.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId");

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Film_API.Models.Character", b =>
                {
                    b.Navigation("CharacterMovies");
                });

            modelBuilder.Entity("Film_API.Models.Movie", b =>
                {
                    b.Navigation("CharacterMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
